---
- name: Install packages
  community.general.pacman:
    name: 
      - gnome
      - sudo
      - vi
      - nano
      - vim
      - git 
      - base-devel
      - go
      - firefox
      - networkmanager
    state: present

- name: Enable GDM
  ansible.builtin.shell: |
    systemctl enable gdm.service

- name: Enabe NetworkManager
  ansible.builtin.shell: |
    systemctl enable NetworkManager.service
   